# Generated by Django 5.2.2 on 2025-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedstring',
            name='text',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
