# Generated by Django 5.2.2 on 2025-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_analyzedstring_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedstring',
            name='character_frequency_map',
            field=models.JSONField(default=dict),
        ),
    ]
